version: "3"
services:
    pm_apache:
        build: .
        image: php:7.4-apache
        container_name: pm_apache
        extra_hosts:
            - "dev.pm.com.ar:127.0.0.1"
        volumes:
            - .:/application:cached
            - .:/app:cached
            - ../www/:/var/www/html
            - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./config/dev.pm.com.ar.conf:/etc/apache2/sites-enabled/dev.pm.com.ar.conf
            - ../logs:/var/log/apache2
        expose:
            - 80
        ports:
            - 80:80
        links: 
            - pm_mysql
            - pm_memcached

    pm_mysql:
        image: mysql:5.7
        container_name: pm_mysql
        ports:
            - 3306:3306
        expose:
            - 3306
        volumes:
            - ../db/working:/var/lib/mysql
            - ../db/backups:/var/db/backups
        environment:
            - MYSQL_DATABASE=pm
            - MYSQL_ROOT_PASSWORD=Secreta007
            - MYSQL_USER=pm
            - MYSQL_PASSWORD=Secreta007
    pm_memcached:
        image: memcached:latest
        container_name: pm_memcached
